name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Linting
        run: npm run lint
        working-directory: ./frontend

      - name: Run Tests
        run: npm run test
        working-directory: ./frontend

      - name: Build Next.js App
        run: npm run build
        working-directory: ./frontend

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend
